### ISSUE TITLE
4th Milestone: CuEVM with cross-contract call and state persistent, Testing of the EVM

### ISSUE THREAD

**Issue by minhhn2910** [sbip-sg/CuEVM#12]
- [x] List the tests that we fail and decide what to do with them (we dont need to fix all corner cases, as long as they do not affect fuzzing we can skip).
- [x] Test complex cross-contract calls in real world scenario (e.g., uniswap). 
- [x] Make it compatible with goevmlab and test integration.
- [x] Precompiled contracts.
- [ ] Performance optimization.

**Comment by minhhn2910** [comment]
@sdcioc  Do you want to do the 5th item in the [state-root-](https://github.com/sbip-sg/CuEVM/pull/26) PR. if not please merge and we close this milestone.
