### ISSUE TITLE
6th Milestone: Enhance fuzzing design, conduct experiments and write research paper.

### ISSUE THREAD

**Issue by minhhn2910** [sbip-sg/CuEVM#28]
Tracker for the final milestone:
- [ ] Measure and optimize performance
- [ ] Fix remaining bugs
- [ ] Optimize fuzzing strategies
- [ ] TBD
